name: 'Portainer Stack Redeploy'
author: FlooflesDev
description: 'Redeploy a Portainer stack with latest images'

inputs:
  portainerUrl:
    description: 'URL to the Portainer instance (e.g., https://example.com:9443)'
    required: true
  accessToken:
    description: 'Portainer API access token'
    required: true
  stackId:
    description: 'ID of stack to be updated (must be integer)'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'refresh-ccw'
  color: 'blue'
